---
# tasks file for 7zip
  - name: Download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z2404-x64.msi
      dest: C:\Users\ansible\konfiguracja

  - name: Install 7-zip on client
    win_package:
      path: C:\Users\ansible\konfiguracja\7z2404-x64.msi
      state: present
