---
# tasks file for security_patches
    - name: Check for available updates
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
        state: searched
      register: win_updates_result

    - name: Install security updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: installed
      when: win_updates_result.updates | length > 0
