---
- hosts: dell
  tasks:

  - name: Create directory for all installers
    win_file:
      path: C:\Users\ansible\konfiguracja
      state: directory

  - name: Download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z2404-x64.msi
      dest: C:\Users\ansible\konfiguracja

  - name: Install 7-zip on client
    win_package:
      path: C:\Users\ansible\konfiguracja\7z2404-x64.msi
      state: present

  - name: Copy firefox installer to client
    win_copy:
      src: /home/gsadmin/Firefox.msi
      dest: C:\Users\ansible\konfiguracja\Firefox.msi

  - name: Install firefox on the client
    win_package:
      path: C:\Users\ansible\konfiguracja\Firefox.msi
      state: present

  - name: Copy global to the client
    win_copy:
      src: /home/gsadmin/GlobalProtect64_NEW.msi
      dest: C:\Users\ansible\konfiguracja\GlobalProtect64_NEW.msi

  - name: install Global protect
    win_package:
      path: C:\Users\ansible\konfiguracja\GlobalProtect64_NEW.msi
      state: present

  - name: Copy eset.zip to client
    win_copy:
      src: /home/gsadmin/eset_padma.zip
      dest: C:\Users\ansible\konfiguracja

  - name: Unzip an eset agent
    win_unzip:
      src: C:\Users\ansible\konfiguracja\eset_padma.zip
      dest: C:\Users\ansible\konfiguracja\eset_padma
      creates: C:\Users\ansible\konfiguracja\eset_padma

  - name: install eset_agent on remote host
    win_package:
      path: C:\Users\ansible\konfiguracja\eset_padma\agent_x64.msi
  
  - name: Copy statlook installer
    win_copy:
      src: /home/gsadmin/Agent-Statlook-10-10-126-10.msi
      dest: C:\Users\ansible\konfiguracja\Agent-Statlook-10-10-126-10.msi

  - name: Install statlook agent
    win_package:
      path: C:\Users\ansible\konfiguracja\Agent-Statlook-10-10-126-10.msi

  - name: Copy TeamViewer.zip to client
    win_copy:
      src: /home/gsadmin/TeamViewer_MSI64.zip
      dest: C:\Users\ansible\konfiguracja 

  - name: Unzip TeamViewer
    win_unzip:
      src: C:\Users\ansible\konfiguracja\TeamViewer_MSI64.zip
      dest: C:\Users\ansible\konfiguracja\TeamViewer_MSI64

  - name: Some delay to avoid installation conflitcs
    win_wait_for:
      timeout: 15

  - name: Install TeamViewer
    win_shell: C:\Users\ansible\konfiguracja\TeamViewer_MSI64\TeamViewer_MSI64\TV_instalacja.ps1

  - name: Some delay to avoid installation conflitcs
    win_wait_for:
      timeout: 15

  #- name: Copy office 365 to client
   # win_copy:
    #  src: /home/gsadmin/OfficeSetup.exe
     # dest: C:\Users\ansible\konfiguracja

  #- name: Installing office 365
   # win_package:
    #  path: C:\Users\ansible\konfiguracja\OfficeSetup.exe
     # state: present

  - name: Remove dir with installers
    win_file:
      path: C:\Users\ansible\konfiguracja
      state: absent
