---
# tasks file for eset
  - name: Copy eset.zip to client
    win_copy:
      src: /home/gsadmin/eset_padma.zip
      dest: C:\Users\ansible\konfiguracja

  - name: Unzip an eset agent
    win_unzip:
      src: C:\Users\ansible\konfiguracja\eset_padma.zip
      dest: C:\Users\ansible\konfiguracja\eset_padma
      creates: C:\Users\ansible\konfiguracja\eset_padma

  - name: install eset_agent on remote host
    win_package:
      path: C:\Users\ansible\konfiguracja\eset_padma\agent_x64.msi
