---
  - name: Copy global to the client
    win_copy:
      src: /home/gregi/GlobalProtect64_NEW.msi
      dest: C:\Users\ansible\konfiguracja\GlobalProtect64_NEW.msi
    
  - name: install Global protect
    win_package:
      path: C:\Users\ansible\konfiguracja\GlobalProtect64_NEW.msi
      state: present
    
