---
- hosts: all
  tasks:
  - name: Copy TeamViewer.zip to client
    win_copy:
      src: /home/gsadmin/TeamViewer_MSI64.zip
      dest: C:\Users\ansible\konfiguracja

  - name: Unzip TeamViewer
    win_unzip:
      src: C:\Users\ansible\konfiguracja\TeamViewer_MSI64.zip
      dest: C:\Users\ansible\konfiguracja\TeamViewer_MSI64

  - name: Some delay to avoid installation conflitcs
    win_wait_for:
      timeout: 15

  - name: Install TeamViewer
    win_shell: C:\Users\ansible\konfiguracja\TeamViewer_MSI64\TeamViewer_MSI64\TV_instalacja.ps1

  - name: Some delay to avoid installation conflitcs
    win_wait_for:
      timeout: 15
      
