- hosts: dell-ella
  tasks:
  - name: Re-register Windows Update DLLs
    become: true
    become_method: runas
    become_user: ansible
    win_shell: |
      $dlls = @(
          "atl.dll",
          "urlmon.dll",
          "mshtml.dll",
          "shdocvw.dll",
          "browseui.dll",
          "jscript.dll",
          "vbscript.dll",
          "scrrun.dll",
          "msxml.dll",
          "msxml3.dll",
          "msxml6.dll",
          "actxprxy.dll",
          "softpub.dll",
          "wintrust.dll",
          "dssenh.dll",
          "rsaenh.dll",
          "gpkcsp.dll",
          "sccbase.dll",
          "slbcsp.dll",
          "cryptdlg.dll",
          "oleaut32.dll",
          "ole32.dll",
          "shell32.dll",
          "initpki.dll",
          "wuapi.dll",
          "wuaueng.dll",
          "wucltui.dll",
          "wups.dll",
          "wups2.dll",
          "wuweb.dll",
          "qmgr.dll",
          "qmgrprxy.dll",
          "wucltux.dll",
          "muweb.dll",
          "wuwebv.dll"
      )

      foreach ($dll in $dlls) {
          try {
              Write-Output "Registering $dll"
              regsvr32.exe /s $dll
          } catch {
              Write-Output "Failed to register $dll"
          }
      }
