---
- name: Periodic scan using usoclient
  block:
    - name: Run usoclient StartInteractiveScan
      ansible.windows.win_command: usoclient StartInteractiveScan
      become: true
      become_method: runas
      become_user: SYSTEM
      ignore_errors: yes

    - name: Pause for 15 minutes between scans
      ansible.builtin.pause:
        minutes: 14

  loop: "{{ range(0, 4) | list }}"  # Repeat scan 2 times for 30 minutes total
